import { motion } from 'framer-motion'
import { Download, FileText, FileType } from 'lucide-react'
import toast from 'react-hot-toast'
import jsPDF from 'jspdf'

interface ExportTranslationProps {
  originalText: string
  translatedText: string
  sourceLang: string
  targetLang?: string
}

export default function ExportTranslation({
  originalText,
  translatedText,
  sourceLang,
  targetLang = 'English'
}: ExportTranslationProps) {

  const exportAsTXT = () => {
    if (!translatedText.trim()) {
      toast.error('No translation to export')
      return
    }

    const content = `Translation Export
==================
Source Language: ${sourceLang}
Target Language: ${targetLang}
Date: ${new Date().toLocaleString()}

Original Text:
--------------
${originalText}

Translated Text:
----------------
${translatedText}
`

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `translation_${Date.now()}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    toast.success('Exported as TXT file!')
  }

  const exportAsPDF = () => {
    if (!translatedText.trim()) {
      toast.error('No translation to export')
      return
    }

    try {
      const doc = new jsPDF()
      
      // Title
      doc.setFontSize(20)
      doc.text('Translation Report', 20, 20)
      
      // Metadata
      doc.setFontSize(10)
      doc.text(`Source Language: ${sourceLang}`, 20, 35)
      doc.text(`Target Language: ${targetLang}`, 20, 42)
      doc.text(`Date: ${new Date().toLocaleString()}`, 20, 49)
      
      // Original Text
      doc.setFontSize(14)
      doc.text('Original Text:', 20, 65)
      doc.setFontSize(10)
      const originalLines = doc.splitTextToSize(originalText, 170)
      doc.text(originalLines, 20, 75)
      
      // Translated Text
      const translatedStartY = 75 + (originalLines.length * 7) + 15
      doc.setFontSize(14)
      doc.text('Translated Text:', 20, translatedStartY)
      doc.setFontSize(10)
      const translatedLines = doc.splitTextToSize(translatedText, 170)
      doc.text(translatedLines, 20, translatedStartY + 10)
      
      // Footer
      const pageHeight = doc.internal.pageSize.height
      doc.setFontSize(8)
      doc.text('Generated by SIH 2025 Translation System', 20, pageHeight - 10)
      
      doc.save(`translation_${Date.now()}.pdf`)
      toast.success('Exported as PDF file!')
    } catch (error) {
      console.error('PDF export error:', error)
      toast.error('Failed to export PDF')
    }
  }

  const exportAsDOCX = async () => {
    if (!translatedText.trim()) {
      toast.error('No translation to export')
      return
    }

    // Create DOCX-like content (HTML that can be opened in Word)
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Translation Report</title>
  <style>
    body { font-family: 'Calibri', sans-serif; margin: 40px; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    .metadata { color: #666; margin: 20px 0; }
    .content { margin: 15px 0; padding: 15px; background: #f9fafb; border-left: 4px solid #2563eb; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>Translation Report</h1>
  
  <div class="metadata">
    <p><strong>Source Language:</strong> ${sourceLang}</p>
    <p><strong>Target Language:</strong> ${targetLang}</p>
    <p><strong>Date:</strong> ${new Date().toLocaleString()}</p>
  </div>
  
  <h2>Original Text</h2>
  <div class="content">
    <p>${originalText.replace(/\n/g, '<br>')}</p>
  </div>
  
  <h2>Translated Text</h2>
  <div class="content">
    <p>${translatedText.replace(/\n/g, '<br>')}</p>
  </div>
  
  <div class="footer">
    <p>Generated by SIH 2025 Translation System</p>
  </div>
</body>
</html>
`

    const blob = new Blob([htmlContent], { type: 'application/msword' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `translation_${Date.now()}.doc`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    toast.success('Exported as Word document!')
  }

  const hasContent = originalText.trim() && translatedText.trim()

  return (
    <div className="flex flex-wrap gap-2">
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={exportAsTXT}
        disabled={!hasContent}
        className="btn-secondary flex items-center gap-2 text-xs"
        title="Export as TXT file"
      >
        <FileText className="w-4 h-4" />
        <span>Export TXT</span>
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={exportAsPDF}
        disabled={!hasContent}
        className="btn-secondary flex items-center gap-2 text-xs"
        title="Export as PDF file"
      >
        <Download className="w-4 h-4" />
        <span>Export PDF</span>
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={exportAsDOCX}
        disabled={!hasContent}
        className="btn-secondary flex items-center gap-2 text-xs"
        title="Export as Word document"
      >
        <FileType className="w-4 h-4" />
        <span>Export DOCX</span>
      </motion.button>
    </div>
  )
}
